<?xml version="1.0" encoding="UTF-8"?>

<!--
File: projectNotes.xml
Description:
This is a component type description for a illustrations component to be used in
any type of project.  All file relations and processes are described in this
file.

Todo:
1) ...


# This is a save state for this file in case we need to pull info out later.

-->

<!DOCTYPE root [
  <!ELEMENT root (section+)>
  <!ELEMENT section (name, sectionID, description, (file | folder | process | setting)+)>
  <!ELEMENT file (name, type, location, dependents, createdBy, description)>
  <!ELEMENT folder (name, key, description, value)>
  <!ELEMENT process (name, type, description)>
  <!ELEMENT setting (name, key, description, type, value)>
  <!ELEMENT key (#PCDATA)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT location (#PCDATA)>
  <!ELEMENT dependents (#PCDATA)>
  <!ELEMENT createdBy (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT sectionID (#PCDATA)>
  <!ELEMENT value (#PCDATA)>
]>

<root>
    <section>
        <name>Component Root Section</name>
        <sectionID>ComponentTypes</sectionID>
        <description>This is the root section for the fontSets component information.</description>
        <section>
            <name>Project Notes Component Information</name>
            <sectionID>projectNotes</sectionID>
            <description>This section contains general project notes component information.</description>
            <setting>
                <name>Installed Components</name>
                <key>installedComponents</key>
                <description>The components from this type which are installed in this project.</description>
                <type>list</type>
                <value></value>
            </setting>
            <setting>
                <name>Valid Component ID Codes</name>
                <key>validIdCodes</key>
                <description>This list contains all the valid note component ID codes that can be used for this component type.</description>
                <type>list</type>
                <value>simpleNotes</value>
            </setting>
            <setting>
                <name>Component Dependencies</name>
                <key>dependencies</key>
                <description>This list contains all the components and their type that this component is dependent on.</description>
                <type>list</type>
                <value></value>
            </setting>
            <setting>
                <name>In Binding List</name>
                <key>inBindingList</key>
                <description>Flag if this component is to be added to the binding list. Not all components need to be in that list.</description>
                <type>boolean</type>
                <value>False</value>
            </setting>
        </section>
    </section>
</root>

