<?xml version="1.0" encoding="UTF-8"?>

<!--
File: projectNotes_init.xml
Description:
This is a component type description for a project note component to be with
all projects.  All file relations and processes are described in this file.

Todo:
1) ...


# This is a save state for this file in case we need to pull info out later.

-->

<!DOCTYPE root [
  <!ELEMENT root (section+)>
  <!ELEMENT section (name, sectionID, description, (file | folder | process | setting)+)>
  <!ELEMENT file (name, type, location, dependents, createdBy, description)>
  <!ELEMENT folder (name, key, description, value)>
  <!ELEMENT process (name, type, description)>
  <!ELEMENT setting (name, key, description, type, value)>
  <!ELEMENT key (#PCDATA)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT location (#PCDATA)>
  <!ELEMENT dependents (#PCDATA)>
  <!ELEMENT createdBy (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT sectionID (#PCDATA)>
  <!ELEMENT value (#PCDATA)>
]>

<root>
    <section>
        <name>Files</name>
        <sectionID>Files</sectionID>
        <description>This section contains the names and information for files of this component type used in the RPM system in this project.</description>
        <section>
            <name>Wiki Home Template File</name>
            <sectionID>wikiHomeFile</sectionID>
            <description>The Home page template file for notes made in this project.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The name of this file.</description>
                <type>string</type>
                <version>False</version>
                <value>Home.txt</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value>WikiNotes</value>
            </setting>
            <setting>
                <name>Version Control</name>
                <key>versionControl</key>
                <description>Is this file under version control?</description>
                <type>boolean</type>
                <value>True</value>
            </setting>
            <setting>
                <name>Dependent Files</name>
                <key>dependents</key>
                <description>The file(s) this file is dependent on.</description>
                <type>list</type>
                <value></value>
            </setting>
        </section>
        <section>
            <name>Wiki Issues Template File</name>
            <sectionID>wikiIssuesFile</sectionID>
            <description>The Issues page template file for notes made in this project.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The name of this file.</description>
                <type>string</type>
                <version>False</version>
                <value>Issues.txt</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value>WikiNotes</value>
            </setting>
            <setting>
                <name>Version Control</name>
                <key>versionControl</key>
                <description>Is this file under version control?</description>
                <type>boolean</type>
                <value>True</value>
            </setting>
            <setting>
                <name>Dependent Files</name>
                <key>dependents</key>
                <description>The file(s) this file is dependent on.</description>
                <type>list</type>
                <value></value>
            </setting>
        </section>
        <section>
            <name>Wiki Home Template File</name>
            <sectionID>wikiNotesFile</sectionID>
            <description>The Notes page template file for notes made in this project.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The name of this file.</description>
                <type>string</type>
                <version>False</version>
                <value>Notes.txt</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value>WikiNotes</value>
            </setting>
            <setting>
                <name>Version Control</name>
                <key>versionControl</key>
                <description>Is this file under version control?</description>
                <type>boolean</type>
                <value>True</value>
            </setting>
            <setting>
                <name>Dependent Files</name>
                <key>dependents</key>
                <description>The file(s) this file is dependent on.</description>
                <type>list</type>
                <value></value>
            </setting>
        </section>
        <section>
            <name>Wiki Home Template File</name>
            <sectionID>wikiSpecificationsFile</sectionID>
            <description>The Specifications page template file for notes made in this project.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The name of this file.</description>
                <type>string</type>
                <version>False</version>
                <value>Specifications.txt</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value>WikiNotes</value>
            </setting>
            <setting>
                <name>Version Control</name>
                <key>versionControl</key>
                <description>Is this file under version control?</description>
                <type>boolean</type>
                <value>True</value>
            </setting>
            <setting>
                <name>Dependent Files</name>
                <key>dependents</key>
                <description>The file(s) this file is dependent on.</description>
                <type>list</type>
                <value></value>
            </setting>
        </section>
    </section>
    <section>
        <name>Folders</name>
        <sectionID>Folders</sectionID>
        <description>This section contains the settings for all the folders needed for processing this component.</description>
        <section>
            <name>Project Wiki Folder</name>
            <sectionID>WikiFolder</sectionID>
            <description>The project wiki notes folder.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The folder where all the project notes are kept.</description>
                <type>string</type>
                <value>WikiNotes</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value></value>
            </setting>
        </section>
    </section>
</root>

