<?xml version="1.0" encoding="UTF-8"?>

<!--
File: fontSets_init.xml
Description:
This is a component type description for an fontSets_init component to be with
all projects.  All file relations and processes are described in this file.

Todo:
1) ...


# This is a save state for this file in case we need to pull info out later.

-->

<!DOCTYPE root [
  <!ELEMENT root (section+)>
  <!ELEMENT section (name, sectionID, description, (file | folder | process | setting)+)>
  <!ELEMENT file (name, type, location, dependents, createdBy, description)>
  <!ELEMENT folder (name, key, description, value)>
  <!ELEMENT process (name, type, description)>
  <!ELEMENT setting (name, key, description, type, value)>
  <!ELEMENT key (#PCDATA)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT location (#PCDATA)>
  <!ELEMENT dependents (#PCDATA)>
  <!ELEMENT createdBy (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT sectionID (#PCDATA)>
  <!ELEMENT value (#PCDATA)>
]>

<root>
    <section>
        <name>Files</name>
        <sectionID>Files</sectionID>
        <description>This section contains the names and information for files of this component type used in the RPM system in this project.</description>
        <section>
            <name>Font Configuration File</name>
            <sectionID>FontConfig</sectionID>
            <description>Font configuration data for all the fonts used in this project.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The name of this file.</description>
                <type>string</type>
                <version>False</version>
                <value>fonts.conf</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value>Fonts</value>
            </setting>
            <setting>
                <name>Version Control</name>
                <key>versionControl</key>
                <description>Is this file under version control?</description>
                <type>boolean</type>
                <value>False</value>
            </setting>
            <setting>
                <name>Dependent Files</name>
                <key>dependents</key>
                <description>The file(s) this file is dependent on.</description>
                <type>list</type>
                <value></value>
            </setting>
        </section>
    </section>
    <section>
        <name>Folders</name>
        <sectionID>Folders</sectionID>
        <description>This section contains the settings for all the folders needed for processing this component.</description>
        <section>
            <name>Project Font Folder</name>
            <sectionID>FontFolder</sectionID>
            <description>The project font folder.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The folder where all the project fonts are kept.</description>
                <type>string</type>
                <value>Fonts</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value></value>
            </setting>
        </section>
    </section>
    <section>
        <name>Font Setup Section</name>
        <sectionID>FontSetup</sectionID>
        <description>This section contains all the settings for a single font.</description>
        <section>
            <name>Typeface Regular</name>
            <sectionID>Regular</sectionID>
            <description>Settings for the regular typeface font.</description>
            <setting>
                <name>File</name>
                <key>file</key>
                <description>File name for this typeface.</description>
                <type>string</type>
                <value>CharisSILR.ttf</value>
            </setting>
            <setting>
                <name>Source</name>
                <key>source</key>
                <description>Path and name of the source font file for this typeface.</description>
                <type>string</type>
                <value>Resouces/lib_share/Fonts/CharisSIL/CharisSILR.ttf</value>
            </setting>
            <setting>
                <name>Shaping</name>
                <key>shaping</key>
                <description>The shaping engine to be used for this typeface.</description>
                <type>string</type>
                <value>Graphite</value>
            </setting>
            <setting>
                <name>Features</name>
                <key>features</key>
                <description>The features that will be used for this typeface.</description>
                <type>list</type>
                <value>liga=1</value>
            </setting>
            <setting>
                <name>Modify</name>
                <key>modify</key>
                <description>Request any modifications for this typeface such as bolding.</description>
                <type>list</type>
                <value></value>
            </setting>
            <setting>
                <name>Mapping</name>
                <key>mapping</key>
                <description>Specify a file that might contain any character mapping modifications.</description>
                <type>string</type>
                <value>None</value>
            </setting>
        </section>
    </section>
</root>

