<?xml version="1.0" encoding="UTF-8"?>

<!--
File: bookTex.xml
Description:
This is a project or Document type description for a book publication to be rendered
with TeX. All file relations and processes are described in this file.

Todo:
1) Add a process section where all processes are described
2) Add file type section that describes each kind of type of file found in the component
3) Need a section to describe project folder attributes <location>
4) Need a default book project section that the system will use to start a project

-->

<!DOCTYPE root [
  <!ELEMENT root (section+)>
  <!ELEMENT section (name, sectionID, description, (setting | file | folder | process)+)>
  <!ELEMENT file (name, type, location, dependents, createdBy, description)>
  <!ELEMENT folder (name, key, description, value)>
  <!ELEMENT process (name, type, description)>
  <!ELEMENT setting (name, key, description, type*, value)>
  <!ELEMENT sectionID (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT key (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT location (#PCDATA)>
  <!ELEMENT dependents (#PCDATA)>
  <!ELEMENT createdBy (#PCDATA)>
  <!ELEMENT value (#PCDATA)>
]>

<root>
    <section>
        <name>Files</name>
        <sectionID>Files</sectionID>
        <description>This section contains the names of all the bookTex files the RPM system will use in this projects.</description>
    </section>
</root>

